### ISSUE TITLE
Component background in AT 0.5.0, framework 3.0

### ISSUE THREAD

**Issue by SteveX** [deltanet/adapt-background-selector#10]
Whilst the article and block image backgrounds work great with Authoring Tool 0.5.0, framework 3.0, the component backgrounds cannot be seen using the AT preview.

**Comment by RobertPeek** [comment]
As the Authoring Tool isn't yet fully compatible with FWv3 I hadn't started to test this in the environment specified so thanks @SteveX for finding this.
